### ISSUE TITLE
Clarify README.md

### ISSUE THREAD

**Issue by MatthyPlayz** [Hexeption/MCP-Reborn#103]
It'd be nice if you could add a note to README.md so that you realize you have to use Java 12, not 8. I had trouble figuring out why my Minecraft instance until I dug through the issues and realized you had to use Java 12.

**Comment by josephworks** [comment]
Java 12? I think Java 11 also works and 8 should.

**Comment by MatthyPlayz** [comment]
8 didn't work for me, kept giving me Exit Code 0

**Comment by josephworks** [comment]
Hmm, so I think that the issue is that java 8 doesn't work and we should get that fixed. Not that we should write on the readme that you have to use 11+

**Comment by josephworks** [comment]
![image](https://user-images.githubusercontent.com/18745823/102727630-ff1c8280-42e3-11eb-95e8-d3c6cc13ec0d.png)

**Comment by josephworks** [comment]
![image](https://user-images.githubusercontent.com/18745823/102727630-ff1c8280-42e3-11eb-95e8-d3c6cc13ec0d.png)

**Comment by josephworks** [comment]
LMAO
java 8 works just fine.
