### ISSUE TITLE
could not run build action using connection to gradle distribution 'https://services.gradle.org/distributions/gradle-4.9-all.zip'

### ISSUE THREAD

**Issue by theone1dev** [Hexeption/MCP-Reborn#109]
i did everything like in this https://www.youtube.com/watch?v=K6KScyIpCtc tutorial and i get this error in problems, why? i use eclipse and if you know what to do, please reply.

**Comment by theone1dev** [comment]
also, its one of my first times using gradle in eclipse

**Comment by Hexeption** [comment]
We don't support eclipse

**Comment by theone1dev** [comment]
oh okay
