### ISSUE TITLE
Not able to reobfuscate

### ISSUE THREAD

**Issue by Wdestroier** [Hexeption/MCP-Reborn#11]
The build script doesn't reobfuscate the game files. Is there any script for reobfuscation?

**Comment by randomperson189** [comment]
I'm having the same issue, I do reobfJar but it doesn't give me the lettered class files like the original MCP did.

**Comment by MGW14** [comment]
DIY. Download the Proguard obfuscation obfuscater (lol) and obfuscate it.

**Comment by barpec12** [comment]
@MGW14 I tried with Proguard, but without success. I tried mappings from mcp, but they didn't work either - jar isn't obfuscated in a way, that minecraft does. Describing how to do this would be helpful for me and others, I suppose.

**Comment by Internal-Exception** [comment]
@barpec12 Did you ever figure this out? Running into the same problem right now. Thanks

**Comment by barpec12** [comment]
@Internal-Exception unfortunately not, I spent a lot of time figuring, how to do this, but without success.
