### ISSUE TITLE
How to add libraries in gradle

### ISSUE THREAD

**Issue by atkn1337** [Hexeption/MCP-Reborn#131]
Hello i want to add a DiscordRPC library its in jitpack repository i added it with compile ' ' but i cant use import but when i try eclipse in build path i can import jar files etc..
this is the build.gradle => https://pastebin.com/U2hEqvH0
i use intellij

**Comment by TheKodeToad** [comment]
You need to add the following underneath `mavenCentral()`:
```gradle
maven { url "https://jitpack.io" }
```

**Comment by atkn1337** [comment]
> 
> 
> You need to add the following underneath `mavenCentral()`:
> 
> ```groovy-gradle
> maven { url "https://jitpack.io" }
> ```

where to add `shade 'com.github.Vatuu:discord-rpc:1.5.0'`

**Comment by atkn1337** [comment]
sorry im stupid i add the wrong library
