### ISSUE TITLE
"Could not set process working directory to '..\MCP-Reborn-1.17\projects\mcp': could not set current directory (errno 3)" when running setupMCP

### ISSUE THREAD

**Issue by ljcool2006** [Hexeption/MCP-Reborn#134]

**Comment by vraddev** [comment]
this is not solved, why is it marked as solved

**Comment by 1s0n** [comment]
I have found a workaround, just run the setupMCP using gradlew.bat

just run gradlew setupMCP using cmd

**Comment by 1s0n** [comment]
nvm

**Comment by andro-32** [comment]
>  I also noticed that there was no mcp folder appearing in the Gradle window.

that is indeed why its not working.

**Comment by joaopinto24** [comment]
you should be running setup inside of mcp folder, which is inside of tasks
![image](https://github.com/Hexeption/MCP-Reborn/assets/132157779/47815e45-e77d-4b8b-aff8-2d444f5c9ad8)
