### ISSUE TITLE
setup not working

### ISSUE THREAD

**Issue by Slausy** [Hexeption/MCP-Reborn#139]
![947EAFBE-3400-4186-9B73-A91F8853C386](https://user-images.githubusercontent.com/78500906/139534614-7e3beb54-d26c-447d-a9a5-ccb34fcb5573.jpg)
I waited 2500 seconds but not finished why does this happen? always stop at 56%

**Comment by Slausy** [comment]
where i get the error is the installation done when i click on the mcp folder setup file

**Comment by Hexeption** [comment]
We don't offer support for Eclipse
