### ISSUE TITLE
Client.json downloads the vanilla client

### ISSUE THREAD

**Issue by QTPah** [Hexeption/MCP-Reborn#143]
I am trying to export my 1.17 client. I watched a tutorial from Kinderrkill. I built the project, there were no errors and i copy-pasted the client.json file from the 1.17 folder. My client.json, client .json id, client.jar and the folder are named the same. But everytime i launch the client it downloads the vanilla 1.17 and launches it. And when i remove the downloads section in the client.json file then my custom client doesn't show up in the installations.

How should the client.json file look like?

**Comment by GersomR-afk** [comment]
follow the instructions in the readme
