### ISSUE TITLE
1.15.2 - No Client Sound

### ISSUE THREAD

**Issue by StackableGold** [Hexeption/MCP-Reborn#15]
No sound is playing when testing version 1.15.2.

After adding a copy of my assets folder sounds play, Perhaps add instructions onto the github page to do this?

**Comment by cristianvintu13** [comment]
> 
> 
> No sound is playing when testing version 1.15.2.
> 
> After adding a copy of my assets folder sounds play, Perhaps add instructions onto the github page to do this?

Hi, can you guide me on how to fix this? I tried to replace the assets folder but still doesen't seem to work. Any help?

**Comment by cristianvintu13** [comment]
For me, adding a copy of assets to my Eclipse workspace still doesn't play the sounds. Any fix?

**Comment by MrButtersDEV** [comment]
I agree instructions are needed. I don't want to start something then have it not work.

**Comment by ayunami2000** [comment]
**FIX**: go to `build.gradle` and find where it says `args '--assetsDir', downloadAssets.output`. replace `downloadAssets.output` with `'./assets'` and copy the assets folder from your minecraft installation over. What i did was I renamed my `.minecraft` assets folder, ran 1.15.2 again to generate _just_ the 1.15.2 assets files, moved the newly generated assets folder from my `.minecraft` to mcp's working directory, and renamed the original assets folder back in my `.minecraft` directory.
