### ISSUE TITLE
Issue: hypocrit

### ISSUE THREAD

**Issue by hobrin** [Hexeption/MCP-Reborn#158]
Imagine you leak full MC decompiled code against the EULA of MCP, and then, you make a new version of MCP where you say this isn't allowed.

**Comment by splatboy20081** [comment]
hypocrit

**Comment by TheKodeToad** [comment]
The code isn't leaked. This is only a tool for decompilation. Even if it did contain all of the code it wouldn't be a leak. The original version of MCP also contained the same notice.

**Comment by hobrin** [comment]
@TheKodeToad @Hexeption 
I think that there might be a misunderstanding. Hexeption leaked MC's decompiled code with optifine in another project. However MCP (and I think minecraft) say that you can't leak code like that.

Then, he creates an MCP clone, and adds a rule similar to that of MCP.

But at the end of the day the rule is pointless legal bullshit anyway.

**Comment by JustRed23** [comment]
What is your point? Mojang even provides mappings for their code to make modding easier... And if sp614x has any problems with Hexeption decompiling his code he would've done something about it already.
