### ISSUE TITLE
How to use this in eclipse?

### ISSUE THREAD

**Issue by dogsout1** [Hexeption/MCP-Reborn#16]
I'm very stupid and haven't coded Minecraft related stuff since 2014 could someone teach me how to use this in eclipse?

**Comment by JustRed23** [comment]
Hey! You probably have two choices:
1. (i recommend this one) Switch over to Intellij, its way easier since intellij helps you with a lot more than eclipse
2. Watch some videos about creating a hacked client (they mostly have the same procedure with setting up stuff)

**Comment by MGW14** [comment]
Shift-Rightclick in the folder where MCP is in and select open power-shell.
Run ".\gradlew.bat genEclipseRuns eclipse" and wait.

When it's done open Eclipse and select the MCP/eclipse folder and then you're done. You may have to import the Project in eclipse but i don't think so

**Comment by dogsout1** [comment]
im able to run it normally but i cant debug Start.java because it doesnt show it in the directory?

**Comment by GamesArsenal96** [comment]
Getting an error that mcp_config.zip doesn't exist.

`File '%PATH%\MCP-Reborn-master\projects\mcp\build\mcp-config.zip' specified for property 'config' does not exist.`

**Comment by GamesArsenal96** [comment]
Did >.\gradlew.bat genEclipseRuns eclipse

Tried using intellij also but didn't work.
I mainly want to get it to work with eclipse because that is my main JavaPlugin coding platform

**Comment by TheKodeToad** [comment]
Not many people do this but you can import Gradle projects into Eclipse the same way you do with Intellij.
Here is how:
1. Right click inside "Package Explorer"
2. Click "Import"
3. Expand "Gradle"
4. Double click "Existing Gradle Project"
5. Press "Next >" if the welcome screen appears
6. Choose the project folder in "Project root directory"
7. Press finish
Specifically for MCP Reborn:
1. In settings.gradle remove this line: "rootProject.name = 'mcp-reborn'"
2. Click the "Gradle Tasks" tab in the panel at the bottom
3. Expand "mcp"
4. Double click "setup"
To run the client:
1. Click the "Gradle Tasks" tab in the panel at the bottom
2. Expand "mcp"
3. Double click "runclient"
