### ISSUE TITLE
1.18.1 not working!

### ISSUE THREAD

**Issue by Alphastein2021** [Hexeption/MCP-Reborn#161]
When I use jdk 17 it says that it is not supported!

**Comment by Pledix** [comment]
jdk 17 but which is? I think you should use Temurin.
You can download here https://adoptium.net/

**Comment by Alphastein2021** [comment]
ok I'll try it

**Comment by Alphastein2021** [comment]
It works! Thanks!

**Comment by Pledix** [comment]
No matter :)
