### ISSUE TITLE
How do I use MCP to decompile/edit the server?

### ISSUE THREAD

**Issue by pete-the-dev** [Hexeption/MCP-Reborn#169]
I have been able to successfully mod the client with MCP-reborn, but noticed that there were some other folders in the directory: src/test/java. Upon researching this, I learned that this was for modding server software. How would I do this? (I don't see a runserver or a build server gradle task)

**Comment by TheKodeToad** [comment]
"src/test" has nothing to do with server side code.

If you want to run the server, you can use my fork, which merges jacobo's changes and updates to 1.18:

https://github.com/TheKodeToad/MCP-Reborn

**Comment by pete-the-dev** [comment]
ok, I will try that. What is src/test for anyways?

**Comment by TheKodeToad** [comment]
By the way, I haven't tested it.

"src/test" is for testing your code. It is used by many projects to test whether the code is reliable.

For example, you may have a function that concatenates strings. If you were trying to do things properly, you'd create a test that checks if the results of that function were correct. Of course, that would be overengineering, but that's just an example.

**Comment by michaelklann** [comment]
I've just spent about 5 hours trying to see how to deobfuscate, edit, reobfuscate and test SERVER code like I used to with MCP back in the ~v1.6.4 days. Am I beating my head on a rock? I want to mod the SERVER, not a client. 

Can anyone tell me if MCP-Reborn will even do this? If not, what will? 
FYI, I'm used to Eclipse but I really don't care what IDE I need to use.

**Comment by vinc3nz** [comment]
@michaelklann 
1. This is not MCP Support.
2. Download the minecraft server jar (I won't explain how).
3. Run decompile once. You should se a message about that the server was not found. Place the server jar where it says and run decompile again.
4. Open Eclipse. There is a project called Server.

@pete-the-dev
Paste [this](https://github.com/Hexeption/MCP-Reborn/blob/1.19/build.gradle#L121) task in your build.gradle and reload. The you have a runserver tasks.
Alternatively you can download the newest MCP-Reborn for 1.19.2.

**Comment by vinc3nz** [comment]
Close this please.

**Comment by PolymorphicAgent** [comment]
sorry i forgot about this
