### ISSUE TITLE
Idk where you would do this so im sorry

### ISSUE THREAD

**Issue by August2211** [Hexeption/MCP-Reborn#17]
Well basically my friend wants to make a map and needs a datapack but i read that code generated by this tool cannot be published so i just wanted to request if u could make an exception if i give all credits of the datapack to you

**Comment by August2211** [comment]
also got no setup file?

**Comment by MGW14** [comment]
This was never made for datapacks. You are decompiling Minecraft to change the whole game. A datapack is just like a mod but easy. If you don't know much about Gradle/w or Java then search for something else. 

Here we are "hacking" or "modifiying" the game to add features that mojang didn't think of. A datapack is a line of commands being executed one after each other.

**Comment by August2211** [comment]
ah oke ty

**Comment by August2211** [comment]
well now that we are at it do you know why that it says collection does not contain a main type when trying to run it?

**Comment by MGW14** [comment]
Can you send me a screenshot?

**Comment by August2211** [comment]
![image](https://user-images.githubusercontent.com/53059031/76462038-4b47a780-63e1-11ea-8440-07e53ad45390.png)

**Comment by August2211** [comment]
Switched to eclipse couldn't figure out intellij

**Comment by MGW14** [comment]
Did you build the Project using Gradle? If not run ./gradlew.bat genEclipseRuns eclipse in the folder your project is

**Comment by August2211** [comment]
mean this? 
![image](https://user-images.githubusercontent.com/53059031/76462309-bf824b00-63e1-11ea-87b4-f2bffbe2e596.png)

**Comment by MGW14** [comment]
Ye and No. Shift-Rightclick and then select Open Power-Shell. Then type in the Command from above. Oh and btw are you german? bc your name

**Comment by August2211** [comment]
cant open power-shell

**Comment by MGW14** [comment]
Uhhh.. Shift-Rightclick on any point in the explorer where no file is

**Comment by August2211** [comment]
Option doesn't pop up

**Comment by MGW14** [comment]
Ok other option... In Eclipse at the bottom is a popup called Gradle Tasks. Click on that and run following tasks in order: "genEclipseRuns" "eclipse" and "setup" then you should be ready togo

**Comment by August2211** [comment]
![image](https://user-images.githubusercontent.com/53059031/76462918-c6f62400-63e2-11ea-90d3-dc92720b5bdb.png)

**Comment by MGW14** [comment]
Subfolder ide and subfolder mcp

**Comment by August2211** [comment]
couldn't find it just did nvm

**Comment by August2211** [comment]
2 errors

**Comment by August2211** [comment]
![image](https://user-images.githubusercontent.com/53059031/76462968-e2612f00-63e2-11ea-8f8e-2deb1add370c.png)

**Comment by MGW14** [comment]
It is one error. In Run Build - Run tasks failed can you open more suberrors?

**Comment by August2211** [comment]
nop

**Comment by August2211** [comment]
just the one did all of the 3 setups

**Comment by August2211** [comment]
it worked this time tho no error

**Comment by August2211** [comment]
Still same error about a main or whatever

**Comment by Hexeption** [comment]
Please just use IntelliJ

**Comment by MGW14** [comment]
Can you send one Message at a time? This isn't WhatsApp.
If you still get this Message i can't help you out. For me it works in eclipse but go use IntelliJ it is easy aswell.

**Comment by August2211** [comment]
Hexeption idk how IntelliJ works though

**Comment by August2211** [comment]
and apparantly not eclipse anymore either

**Comment by MGW14** [comment]
Just so you know this error occurs because there is no minecraft client. You have to BUILD it first.
Using: ".\gradlew.bat genEclipseRuns eclipse setup"
Then open it in eclipse. Try to refollow these steps and close the issue

**Comment by August2211** [comment]
BUILD FAILED in 0s
2 actionable tasks: 2 executed

**Comment by MGW14** [comment]
How is this going to help me????

**Comment by August2211** [comment]
idk?

**Comment by MGW14** [comment]
I'm Sorry i can't help you with this issue
