### ISSUE TITLE
Cant publish any code provided by this tool.

### ISSUE THREAD

**Issue by Pichuminer** [Hexeption/MCP-Reborn#19]
When you mentioned this, I got very confused.
Are we not able to share our project, or can we not show the source code once we are finished?

**Comment by CoolJWB** [comment]
If you read the [commerial usage guidelines](https://account.mojang.com/terms?ref=ft#commercial) you can find that 

### **EXTENDED FUNCTIONALITY AND “MODS”**
If you comply with and follow the Essential Requirements (in the Brand and Asset Usage Guidelines) and Naming Guidelines above YOU MAY distribute or make available plug-ins and other bits and pieces of extended functionality etc. that you create (together, "Mods") for free and without any charge, but not if the purpose of your Mod is to advertise or promote other products or services (see the section below on Building Promotions with Minecraft). **By "Mods," we mean something original that you created that doesn't contain a substantial part of our copyrightable code or content.** We have the final say on what constitutes a Mod and what doesn't. When you combine your Mod with the Minecraft software, we will call that combination a "Modded Version" of the Game. You MAY NOT distribute any Modded Versions of our Game or software, though you may distribute Mods. You may make money from Mods as described below in the section, "Servers and Hosting."

**Comment by Pichuminer** [comment]
> If you read the [commerial usage guidelines](https://account.mojang.com/terms?ref=ft#commercial) you can find that
> 
> ### **EXTENDED FUNCTIONALITY AND “MODS”**
> If you comply with and follow the Essential Requirements (in the Brand and Asset Usage Guidelines) and Naming Guidelines above YOU MAY distribute or make available plug-ins and other bits and pieces of extended functionality etc. that you create (together, "Mods") for free and without any charge, but not if the purpose of your Mod is to advertise or promote other products or services (see the section below on Building Promotions with Minecraft). **By "Mods," we mean something original that you created that doesn't contain a substantial part of our copyrightable code or content.** We have the final say on what constitutes a Mod and what doesn't. When you combine your Mod with the Minecraft software, we will call that combination a "Modded Version" of the Game. You MAY NOT distribute any Modded Versions of our Game or software, though you may distribute Mods. You may make money from Mods as described below in the section, "Servers and Hosting."

Oh, okay! As long as we don't show any decompiled code, we will be okay.
