### ISSUE TITLE
where tf is like everything

### ISSUE THREAD

**Issue by cakefarmer** [Hexeption/MCP-Reborn#204]
I'm trying to make a 1.18.1 client, but I legit can't find anything. I'm familiar with 1.8.8 mcp, and I can find everything there. Did I compile it wrong or something?
![image](https://user-images.githubusercontent.com/84677260/173113111-da16deda-c9de-4883-8e31-8d227921a814.png)
![image](https://user-images.githubusercontent.com/84677260/173113186-778cca97-438d-411b-9578-ad7c0b96319a.png)

**Comment by TheKodeToad** [comment]
You need to do ./gradlew setup first. Backup everything in src/main/java in case it is erased.

**Comment by cakefarmer** [comment]
Thank you that worked

**Comment by josephworks** [comment]
> Thank you that worked

Great! Glad to hear that! Now close the issue, please.
