### ISSUE TITLE
mcp-reborn intellij

### ISSUE THREAD

**Issue by BlackSnowDot** [Hexeption/MCP-Reborn#207]
For Importing i use "Get From VCS"
When Imported it was Builded Automatically And Nothing happened After "Configure Projects" (i Wait 10 Minute) 
note: 
![image](https://user-images.githubusercontent.com/95581741/175837332-7acee682-9bec-4bb8-aa9f-0c43af1a8d58.png)
Any Idea for fix?

**Comment by josephworks** [comment]
> For Importing i use "Get From VCS" When Imported it was Builded Automatically And Nothing happened After "Configure Projects" (i Wait 10 Minute) note: ![image](https://user-images.githubusercontent.com/95581741/175837332-7acee682-9bec-4bb8-aa9f-0c43af1a8d58.png) Any Idea for fix?

Be sure that your computer has sufficient computing power, and that IntelliJ has enough ram.

This is not an issue with MCP-Reborn, so please close this.

**Comment by vinc3nz** [comment]
Close this please.
