### ISSUE TITLE
Missing server code

### ISSUE THREAD

**Issue by Awakened-Redstone** [Hexeption/MCP-Reborn#21]
As I can see this tool only provides Minecraft Client code, bot not Minecraft server code.
I would like to be able to decompile Minecraft server to see how it generates structures.

_If it feels incomplete please warn me._

**Comment by Tylerinooo** [comment]
Just decompile the server jar that minecraft gives you

**Comment by Awakened-Redstone** [comment]
Hummmm. MCP-rebon allow me to do so?
If yes, how?
Or MCP Still woking for 1.13+ servers?

**Comment by Tylerinooo** [comment]
Hex hasn't setup the server code with his mcp version, and the original mcp only goes up to 1.12.2

**Comment by cosmicdan** [comment]
If you run the setup gradle task, it's all there. The Dedicated Server is not "different" to the base MC game, but rather a subset of it. MCP has all the server side stuff, and you can run a dedicated server with it even.

In other words, no - you're wrong. MCP-Reborn lets you mod server side stuff fine, I'm looking at the world decoration and structure generation code in my IDE right now.
