### ISSUE TITLE
What Theme?

### ISSUE THREAD

**Issue by Hedreon** [Hexeption/MCP-Reborn#214]
What IntelliJ IDEA Theme did you use in that screenshot below?

https://user-images.githubusercontent.com/4052647/46925924-71b7b680-d026-11e8-9c29-e3ed2e43f810.png

**Comment by josephworks** [comment]
> What IntelliJ IDEA Theme did you use in that screenshot below?
> 
> https://user-images.githubusercontent.com/4052647/46925924-71b7b680-d026-11e8-9c29-e3ed2e43f810.png

Material Theme with Atom Icons.

Please close this if you do not have more questions.
