### ISSUE TITLE
Need some help with MCP Reborn that relates to things like texture location, and entity brain location(s).

### ISSUE THREAD

**Issue by ghost** [Hexeption/MCP-Reborn#216]
Yo sup! hope all who work on mcp are well! Recently, I've been trying out MCP and I gotta say for overall code digging, this is really useful! however, I have trouble finding things that I do wanna look more into like the Textures file location and the entity brain location. would any of u know where they are? if so please reply!

Thank you! Cheers!

**Comment by nyan1337** [comment]
> the entity brain location

The package `net.minecraft.world.entity.ai` might be interesting

**Comment by vinc3nz** [comment]
Close this please. If the error persists, please open a new issue or write it here. For other support there also is [Hexceptions Discord](https://discord.gg/7vTth5X9pn).

**Comment by ghost** [comment]
Oh my bad, i forgot to. Thank you for the work you do!!
