### ISSUE TITLE
Why is this labelled reborn? Where is the original MCP?

### ISSUE THREAD

**Issue by scottpedia** [Hexeption/MCP-Reborn#219]
I've been reading online and it seems to me that the MCP everybody is talking about is no longer available. And why is this project named "reborn"? Is the original MCP dead?

**Comment by vinc3nz** [comment]
Mcp can be found under modcoderpack.com. And yes, it is dead since version 1.12

**Comment by vinc3nz** [comment]
Or at least it is dead since 1.14,were Mojang mappings were introduced

**Comment by scottpedia** [comment]
@vinc3nz alright thx for your answers!
