### ISSUE TITLE
Can't get to run the client (1.15.2)

### ISSUE THREAD

**Issue by TheMode** [Hexeption/MCP-Reborn#22]
Here the error I get while trying to run the Start class:
https://pastebin.com/rf8bm20R

Am I doing something wrong? Also getting an error while trying the build gradle method

I am running the lastest version of MacOS and using java 11

**Comment by BriceFab** [comment]
Do you use Java JDK ? Or you have JRE ?

**Comment by TheMode** [comment]
Here the output of my java -version:

java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

(sorry, I do run java 13 and not 11 as I thought)

**Comment by DreamTexX** [comment]
I've got the same problem

**Comment by TheMode** [comment]
I confirm that the problem is specific to macOS (tried on windows with the same steps and it worked).
The start on first thread JVM arg does not seem to fix the issue.

**Comment by DreamTexX** [comment]
Nope, I am on windows and got the same problem (JDK 13)

**Comment by TheMode** [comment]
Guess that the problem can also be because of the JDK version, my Windows is running java 8. My bad.

**Comment by jaradkears** [comment]
Are you using intellij? If so it comes with its own version of the JDK its a custom version of java 11. This is a problem specific to Java 11. If you go into the settings in intellij and change the SDK you can download 14 from the menu.That will fix this.
