### ISSUE TITLE
I keep having this issue when trying to setup the environment for eclipse.

### ISSUE THREAD

**Issue by GamesArsenal96** [Hexeption/MCP-Reborn#23]
Did '.\gradle.bat genEclipseRuns eclipse'

But it keeps freezing at 50%, ran it multiple times but keep getting the same error: 
![cmd-0956PM](https://user-images.githubusercontent.com/24835664/78465796-a22e5d00-76bf-11ea-90c2-8c1d32b1d61b.png)

Any way to fix this...

**Comment by crab-in-the-northeast** [comment]
I have the same problem.
