### ISSUE TITLE
Cannot run builded jar

### ISSUE THREAD

**Issue by Zayceur** [Hexeption/MCP-Reborn#26]
Hello guys,

When I run the gradle command `runclient`, everything works fine and as intended.

However, I cannot start the jar compiled with the build command (located in `build/libs`).

Here's what I tried and the errors.

Running the jar using the Minecraft launcher :
```Caught previously unhandled exception :
java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.client.Minecraft
	at net.minecraft.client.main.Main$2.run(Main.java:122)
```

Running the jar directly using command-line (`java -cp mcp-reborn-1.0.0.jar net.minecraft.client.main.Main`) : 
```ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Exception in thread "main" java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/Hash$Strategy
        at net.minecraft.client.main.Main.main(Main.java:59)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.Hash$Strategy
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 1 more
```

Running the jar directly using the command-line with the mcp Start class (`java -cp mcp-reborn-1.0.0.jar mcp.client.Start`) : 
```ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Exception in thread "main" java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/Hash$Strategy
        at net.minecraft.client.main.Main.main(Main.java:59)
        at mcp.client.Start.main(Start.java:17)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.Hash$Strategy
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 2 more
```

Does anyone know how to debug this ?

Thanks in advance !

**Comment by 0ctave** [comment]
I have the same problem :/

**Comment by MenschenToaster** [comment]
I have the same problem too

**Comment by AutogolazzoJr** [comment]
I also have this problem. Does the creator expect us to only use this in offline-mode?

**Comment by 0ctave** [comment]
I tried to troubleshoot, but I didn't found a way to resolve it, and I still don't understand why it can't initialize the class, does someone have an idea ?

**Comment by Zayceur** [comment]
I already tried to add every dependencies using the command line but then it asks me a net.minecraft dependency that I couldn't find.

**Comment by 0ctave** [comment]
I found the problem !!
There is some missing files in the outputed Jar, you need to add the files from client-extra
Else the class TranslationTextComponent isn't initialized properly and it break everythings

**Comment by AutogolazzoJr** [comment]
> I found the problem !!
> There is some missing files in the outputed Jar, you need to add the files from client-extra
> Else the class TranslationTextComponent isn't initialized properly and it break everythings

Where is this "client-extra" thing? Thanks.

**Comment by Zayceur** [comment]
Thanks a lot @0ctave. Copying the content of client-extra.jar (except the META-INF folder) into a resources folder did the trick !

Perhaps it would be a good thing to add this into the "setup" script in order to do that automaticaly @Hexeption.

**Comment by KdotDevelopment** [comment]
how did you edit the json file to make it run in the first place? @Zayceur

**Comment by kingdevnl** [comment]
You can't just do java -cp mcp-reborn-1.0.0.jar net.minecraft.client.main.Main

**Comment by kingdevnl** [comment]
You are supposed to run the jar true the Minecraft launcher.
Please join the discord for support:
https://discord.gg/SxwZRS5

**Comment by AutogolazzoJr** [comment]
> You are supposed to run the jar true the Minecraft launcher.
> Please join the discord for support:
> https://discord.gg/SxwZRS5

Nobody is having that problem. The problem is that the built jar doesn't have any of the requires files found in client-extras.jar.

**Comment by KdotDevelopment** [comment]
what is the client-extras.jar and how do i add it to the built jar?

**Comment by MenschenToaster** [comment]
I fixed it! You need to put "asssets" and "data" from the normal Minecraft Jar(just use a Unzipper to get the files) of your Version in the resources folder! http://prntscr.com/semq04

when you don't have it make a folder called resources in src/main

**Comment by MenschenToaster** [comment]
Oh you also need to add these other files from the Minecraft jar! It needs to lock like this: http://prntscr.com/semqzu

**Comment by CanVo** [comment]
> Oh you also need to add these other files from the Minecraft jar! It needs to lock like this: http://prntscr.com/semqzu

Thank you so much for this mention, I was running into the issue as well and got mine to run via MC launcher. Cheers!

**Comment by balaramsudip** [comment]
How do you run the jar through the Minecraft Launcher?
