### ISSUE TITLE
No Sound in game (1.19.4)?

### ISSUE THREAD

**Issue by TheJoetube** [Hexeption/MCP-Reborn#270]
As stated, theres no sound in game, I have tried running the copyAssets and downloadAssets tasks but nothing changed.

**Comment by APie357** [comment]
Try to run the Gradle task `copyAssets`.
```sh
./gradlew copyAssets
```

**Comment by TheJoetube** [comment]
> Try to run the Gradle task `copyAssets`.
> 
> ```shell
> ./gradlew copyAssets
> ```

that doesnt fix it

**Comment by APie357** [comment]
Try to copy the `.minecraft/assets` folder into your project's `run` folder. Make sure that you ran that version of Minecraft before.

**Comment by TheJoetube** [comment]
> Try to copy the `.minecraft/assets` folder into your project's `run` folder. Make sure that you ran that version of Minecraft before.

did all of that and it still doesnt work

**Comment by TheJoetube** [comment]
> Try to copy the `.minecraft/assets` folder into your project's `run` folder. Make sure that you ran that version of Minecraft before.

in general, any code I edit doesnt change anything about the compiled game

**Comment by APie357** [comment]
Then I can't help you with that. Sorry!
