### ISSUE TITLE
My Ubuntu PC crashes on decompilation.

### ISSUE THREAD

**Issue by coderamen666** [Hexeption/MCP-Reborn#278]
When I try running the setup task, it crashes my terminal application. My PC only has 4 gb of ram and has a terrible Pentium branded modern processor from the late 2010s. Help?

Also: I was the person that added server support. My GitHub password for that old account is lost so I made a new one.

**Comment by VadSzil42** [comment]
Hi!
Same problem, but on Windows. I have tried five Gradle editors to run build.gradle.  None of them works.
I have an old Dell Inpiron 13 7000 with Win10 on it. 4G RAM too.
I also tried the MCP from modcoderpack.com, but they are old, and they are not really working.
And the original Gradle editor crashes too.

**Comment by coderamen666** [comment]
I ran it from the command line with nothing else running. It might just be that we aren't meeting system requirements

**Comment by VadSzil42** [comment]
Your command line is messing up with the setup task, isn’t it?
If you need 1.8 or 1.8.8 MCP, then try these: (pre-decomplied MCP builds)
1.8: https://github.com/ZeroedInOnTech/1.8
1.8.8: https://github.com/ZeroedInOnTech/1.8.8
Sadly, I want the 1.20 MCP… which I don’t think that is available in predecomplied version.

**Comment by VadSzil42** [comment]
Oh, I have another idea.
Install VMWare Workstation to your computer, then grab another Ubuntu ISO file from the original website. Then make an Ubuntu VM.
Then use the VM settings menu to give the VM 8 or 16G RAM from the swapfile.
Finally, import the whole GitHub repo to the VM using Shared Folders.

I hope this will work.

**Comment by coderamen666** [comment]
Eh, I can do without I guess.
