### ISSUE TITLE
build.gradle not working (1.20)

### ISSUE THREAD

**Issue by VadSzil42** [Hexeption/MCP-Reborn#307]
Hi all!
I ran build.gradle with Gradle 8.5 and got the following error:
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.
 
> Configure project :
 Java: 17.0.8 JVM: 17.0.8+7-Debian-1(Debian) Arch: amd64
 
FAILURE: Build failed with an exception.
 
* What went wrong:
**Task 'build.gradle' not found in root project 'mcp-reborn' and its subprojects.**
 
* Try:
> Run gradle tasks to get a list of available tasks.
> For more on name expansion, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:name_abbreviation in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
 
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
 
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
 
For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
 
BUILD FAILED in 28s
 

System specs:
Kali Linux 2023.4 with Gradle 8.5 and Java 17.0.8
HP ProLiant ML310e Gen8 v2
Let me know if you need more info!

Please reply soon!

**Comment by yusufumben09** [comment]
same

**Comment by TeaLoverWithPing** [comment]
same

**Comment by SchoolTARMaster** [comment]
Don’t run `gradle build.gradle`, instead run `gradle build`.

**Comment by SchoolTARMaster** [comment]
I mean use the gradle wrapper

**Comment by VadSzil42** [comment]
Thx will check it

**Comment by SchoolTARMaster** [comment]
Note use `./gradlew build` on linux. Any other task, use `./gradlew <task name>`.

**Comment by VadSzil42** [comment]
@SchoolTARMaster thanks it worked

**Comment by SchoolTARMaster** [comment]
> @SchoolTARMaster thanks it worked

Your welcome.
