### ISSUE TITLE
How to make a zoom function + compile/obfuscate?

### ISSUE THREAD

**Issue by gitozify** [Hexeption/MCP-Reborn#31]
I'm loving MCPReborn so much, seeing Minecraft in a whole new dimension, especially with the code.

However, I'm wondering about how you can make a zoom function similar to Optifine? That's something I've wanted to add, however, I don't know how to.

And, how can I obfuscate or compile my mod when I'm finished?

**Comment by MrButtersDEV** [comment]
Hexeption has an optifine src resource which integrates optifine into your project but I don't think it has anything able 1.12

**Comment by mememasterlord32345** [comment]
Just change your fov to a low value to make a zoom effect

**Comment by balaramsudip** [comment]
To obfuscate your code, use ProGuard
