### ISSUE TITLE
Decompiling 1.16.1 server

### ISSUE THREAD

**Issue by Venji10** [Hexeption/MCP-Reborn#39]
Hello, 
I would like to know, where I have to place the server jar for decompiling.
And do I have to execute any extra gradlew commands or is decompiling server included in gradlew setup?

**Comment by balaramsudip** [comment]
You have to wait till MCPBot publishes 1.16.1 mappings

**Comment by Venji10** [comment]
@balaramsudip when can I expect that and how can I notice the release?
