### ISSUE TITLE
Cannot setup MCPR

### ISSUE THREAD

**Issue by UppsetDave** [Hexeption/MCP-Reborn#42]
Whenever I import/open build.gradle all the files that are shown in the how to use section images are different from what I get and cannot find the setup script, if I may sound like a noob I have never used intelij before or had any success with any tools to decompile/edit minecraft.

**Comment by MenschenToaster** [comment]
https://www.youtube.com/watch?v=20nqRfHL3us
This should help you 😉

**Comment by UppsetDave** [comment]
Oh thx @MenschenToaster

**Comment by MenschenToaster** [comment]
Well it isn't my Video 😉

**Comment by MenschenToaster** [comment]
@Hexeption made the Video.
I am just a random guy using this Project for my Minecraft Legit Client

**Comment by UppsetDave** [comment]
Btw how the heck do i compile the client

**Comment by UppsetDave** [comment]
@MenschenToaster

**Comment by MenschenToaster** [comment]
you just run build/jar...

**Comment by UppsetDave** [comment]
ok
