### ISSUE TITLE
How to make a playable jar I can launch from the launcher

### ISSUE THREAD

**Issue by UppsetDave** [Hexeption/MCP-Reborn#43]
When I build the project I do not know where it places the files tht I can pack into the jar.

**Comment by SemmieboyYT** [comment]
It is possible to follow the instructions here: https://m.imgur.com/a/YLqClkW

You can change the name!(1.14.4.wdl) to whatever you want. Just make sure everything is named like that. If you still get a error, do this as well: https://github.com/Hexeption/MCP-Reborn/issues/41#issuecomment-656205239

**Comment by UppsetDave** [comment]
Ok i will try this later

**Comment by balaramsudip** [comment]
java -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -cp Minecraft.jar net.minecraft.client.main.Main --accessToken PlayerDev --version 1.16.1
