### ISSUE TITLE
1.16.1 wont start in the launcher

### ISSUE THREAD

**Issue by SemmieboyYT** [Hexeption/MCP-Reborn#44]
First, I know there is no 1.16.1 release yet, but if I download it straight away its set on 1.16.1. I know its most likely not supported because of that. But maybe someone can help me fix this?

Anyway so what happened is I just build the client (it has some small modifications) and I copied the data and assets folder into it, copied a json file over, renamed everything, changed the json so it won't download the vanilla jar again and changed the id in the json. But when I started it, I got this crash: [crash-2020-07-13_20.14.46-client.txt](https://github.com/Hexeption/MCP-Reborn/files/4914367/crash-2020-07-13_20.14.46-client.txt)

Please respond if you know how to fix this.

**Comment by ramonrpa** [comment]
I've got the same problem

**Comment by ramonrpa** [comment]
I managed to fix the problem. You only need to copy the folders: data and assets to the final jar. After that, you need to create the pack.mcmeta inside the final jar with the following informations:
` {
    "pack": {
        "description": "The default data for Minecraft",
        "pack_format": 5
    }
}`

**Comment by SemmieboyYT** [comment]
That makes sense, thanks!
