### ISSUE TITLE
Can i use this to make a hack client (for personal use and friends)

### ISSUE THREAD

**Issue by c0d3rb0y** [Hexeption/MCP-Reborn#48]
No commercial distribution. Just wanna make a small hack client for my friends who do not know how to add Baritone to their mod folder. And yes i will give credit.

**Comment by splatboy20081** [comment]
Buddy, hacked clients are against Minecrafts EULA and making one could get your account terminated.

**Comment by splatboy20081** [comment]
Also, using one on a multiplayer server will almost always get you banned. So, please do not make one.

**Comment by c0d3rb0y** [comment]
ok but can i make an optifine client then

**Comment by splatboy20081** [comment]
Sorry, but you can't. If it involves baritone or any hacks it is violating EULA, and optifine is not meant to be made as a client.

**Comment by c0d3rb0y** [comment]
shit

**Comment by Apmunute** [comment]
do the illegal

**Comment by splatboy20081** [comment]
@Apmunute what is up with you

**Comment by IMS212** [comment]
do not do the illegal, optifine is not allowed to be redistributed in any form

**Comment by Roizor** [comment]
do the funny

**Comment by IMS212** [comment]
**don't do the funny**
