### ISSUE TITLE
About ProGuard

### ISSUE THREAD

**Issue by balaramsudip** [Hexeption/MCP-Reborn#58]
What would be the best way to obfuscate this with ProGuard? I am asking because proguard has so much optimization to shrinking, obfuscation, and more. So, how would you use ProGuard with MCP-Reborn?

**Comment by TheAwesome98-Real** [comment]
Why would you want to obfuscate your client?

**Comment by FinnT730** [comment]
@TheAwesome98-Real Since it is likely an hacked client, and he wants to make it hard for Mojang to decompile likely...
And if that is the case, he is breaking the EULA / TOS of Mojang XD

**Comment by TheAwesome98-Real** [comment]
But... mojang won’t decompile the client?

**Comment by FinnT730** [comment]
They likely wont, but making custom / utility / hacked clients IS against the license of the game. 
They likely wont don't do anything against it, but they have a legal team from Microsoft, so if they want, they can sue so many people at once for making such thing.

And like you said, why obfuscate something when... ahh never mind, the person that want this has hidden intend, hiding something, that could be dangerous for the person downloading / using it.

**Comment by balaramsudip** [comment]
I am pretty sure mojang wants you to obfuscate your mod code before publishing it. That is why I asked.

**Comment by balaramsudip** [comment]
I am not making a hacked client, but I am pretty sure that mojang doesn't want people outside of minecraft to get their hands on the code, as they said in the EULA that redistributing any part of the game is illegal, and I asked because of this.

**Comment by Ultimate-7777** [comment]
Then why would you want to obfuscate the client ¯\_(ツ)_/¯

**Comment by TheAwesome98-Real** [comment]
You aren't technically redistributing the code, you're distributing a modified jarfile, which is allowed. The code is compiled, and can't be read without a decompiler, which technically isint your fault
