### ISSUE TITLE
How to login intellij ?  McpReborn 1.16.2 w/Optifine

### ISSUE THREAD

**Issue by XiohAtk** [Hexeption/MCP-Reborn#66]
I can't seem to find out a working way to Login using intellij
I have setup McpReborn with Optifine and its working on 1.16.2 just can seem to find out how to login to my McAccount

**Comment by TheAwesome98-Real** [comment]
Add them as arguments for the jar when opened. I’m not sure how to do it in IntelliJ, but a google search for “intellij jar arguments” should find it.

**Comment by TheAwesome98-Real** [comment]
And “Minecraft login details jar arguments” as well.

**Comment by higgy999** [comment]
The second method found in this blog post works. If you are using Optifine with your client you can add the code into Start.java and adapt it to work. I have attached a file that has it. Replace the username and password with yours in the method call and gitignore the start method to not post your password.

https://pastebin.com/2UaxCri3

**Comment by TheAwesome98-Real** [comment]
> The second method found in this blog post works. If you are using Optifine with your client you can add the code into Start.java and adapt it to work. I have attached a file that has it. Replace the username and password with yours in the method call and gitignore the start method to not post your password.
> 
> https://pastebin.com/2UaxCri3
> https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/modification-development/2915357-tutorial-how-to-login-using-legit-minecraft

yeah, this.
