### ISSUE TITLE
How to add Baritone into my project

### ISSUE THREAD

**Issue by SirObby** [Hexeption/MCP-Reborn#67]
Recently 1.16.2 Baritone released and i dont know how to implement it into my MCP-Reborn project.
And dont want to try out forgegradle
So if anyone willing to help could make a Tutorial for not just me but others for implementing Baritone to MCP-Reborn.

**Comment by TheAwesome98-Real** [comment]
Add the baritone source code (google: “baritone source code”) into your project directory.

**Comment by TheAwesome98-Real** [comment]
`src` folder i meant.

**Comment by SirObby** [comment]
And where might i find that?

**Comment by SirObby** [comment]
have u done it?

**Comment by Ultimate-7777** [comment]
https://github.com/cabaletta/baritone @SirObby

**Comment by TheAwesome98-Real** [comment]
> https://github.com/cabaletta/baritone @SirObby

Yes, this is what I meant.

**Comment by SirObby** [comment]
Can you make a tutorial for implemenitng baritone to it?

**Comment by TheAwesome98-Real** [comment]
> Can you make a tutorial for implemenitng baritone to it?

No. You should only have to copy the Baritone `src` folder over the Minecraft `src` folder, and replace any files.
