### ISSUE TITLE
Can you publish the .jar?

### ISSUE THREAD

**Issue by splatboy20081** [Hexeption/MCP-Reborn#75]
Are you legally allowed to publish the jar, but not the code?

- Splatboy Dev

**Comment by FinnT730** [comment]
Nope, since that would break the EULA of Minecaft

**Comment by splatboy20081** [comment]
Send a screenshot of the part that violates, since it has no hacks.

**Comment by splatboy20081** [comment]
Ah, found it. So, how exactly can Badlion and Lunar be allowed?

**Comment by splatboy20081** [comment]
@FinnT730

**Comment by FinnT730** [comment]
> Ah, found it. So, how exactly can Badlion and Lunar be allowed?

They are not. If mojang really wanted to, they could sue these people, and demand that they pay quite a lot. I may not sure why they don't do it, but not my problem.

Also, don't use badlion, it does crap to your pc, and has some evil detections that will be used on you, and might even record gameplay without you knowing it (from what I have heard, from people)

**Comment by splatboy20081** [comment]
Optifine-style would be allowed though

**Comment by balaramsudip** [comment]
I am pretty confident that you can publish the jar if you obfuscate the code.

**Comment by CoolJWB** [comment]
> I am pretty confident that you can publish the jar if you obfuscate the code.

No that's still a violation of the EULA. If you obfuscate the code it doesn't matter because the code is still the same, just not humanly readable (otherwise it wouldn't execute).
Furthermore the jar file is also a collection of assets such as textures, fonts and more. Obfuscation of the code wouldn't be enough...

**Comment by FinnT730** [comment]
> Optifine-style would be allowed though

Yes, optifine is against the TOS as well, but it is not my problem. Mojang should deal with that.
Creating modified clients, is also against the TOS, so don't do it. Unless you want legal trouble, if they start to hunt clients

**Comment by splatboy20081** [comment]
just going to say it's not TOS, but EULA.
