### ISSUE TITLE
MCP 1.16.3

### ISSUE THREAD

**Issue by rissoru1592** [Hexeption/MCP-Reborn#79]
I get this error when opening the file with intelliJ IDE:
``
Unable to load class 'org.apache.http.Consts'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
``

**Comment by funkemunky** [comment]
This is an issue that is also occurring for me.
