### ISSUE TITLE
Obfuscation Maps From 1.14 On Aren't Being Used.

### ISSUE THREAD

**Issue by higgy999** [Hexeption/MCP-Reborn#82]
If they are available they should be used.

**Comment by Ultimate-7777** [comment]
They are available, but Mojang's TOS on the Maps are super restricting. You can't use the maps to make a hacked client, or others. Essentially, they could sue you if u misused the mappings.

**Comment by higgy999** [comment]
> They are available, but Mojang's TOS on the Maps are super restricting. You can't use the maps to make a hacked client, or others. Essentially, they could sue you if u misused the mappings.

Although I see where your coming from, I don't think MCP Reborn would be held responsible since they provide the tool and in the readme say not to post the source code of the client and server.
