### ISSUE TITLE
publishing?

### ISSUE THREAD

**Issue by minecraft3r217** [Hexeption/MCP-Reborn#83]
when do you plan to make it so we can publish our code so we can use it in a normal client?

**Comment by splatboy20081** [comment]
uhhh... why did you open it and close it?

**Comment by minecraft3r217** [comment]
figured it out

**Comment by amalte** [comment]
I am having this problem right now, how did you solve it? I don't know how to compile and get the jar file to run in the normal minecraft launcher.

**Comment by splatboy20081** [comment]
different question
