### ISSUE TITLE
Where can I edit/find the default textures?

### ISSUE THREAD

**Issue by PhoenixXKN** [Hexeption/MCP-Reborn#91]
As stated in the title, I'd like to edit/change minecraft's default textures for smaller ones so that it loads them quicker; But after executing the gradle build Task, i looked into the .jar and couldn't find the default textures... so, where are they located? Thanks in advance

**Comment by Bigmancozmo** [comment]
Hey... How do you do this? Almost everywhere I find someone that asks this question just closes it and/or says they figured out how, without saying HOW to do it.
