### ISSUE TITLE
Plz i need halp : eclipse frizes on setup

### ISSUE THREAD

**Issue by NikunjChiluvuri** [Hexeption/MCP-Reborn#95]
the owener closed my old issue #94 .  but i really want to decompile 1.16.4. can you plz tell the commands that i can run on windows power shell? and plz dont close this issue.

**Comment by NikunjChiluvuri** [comment]
yea dont close it

**Comment by Hexeption** [comment]
gradle setup

**Comment by NikunjChiluvuri** [comment]
ok thx
